const actions = {
    GET_ALL_USERS: "GET_ALL_USERS",
    AUTH: 'AUTH',
    UPDATE: 'UPDATE',
    CHANNEL: 'CHANNEL',
    MESSAGE: 'MESSAGE',
    EMOTICON: 'EMOTICON',
    TYPING: 'TYPING',
    ERROR: "ERROR",
    FILES:"FILES", 
    STATUS: "STATUS",
    CREATE_CHANNEL: "CREATE_CHANNEL",
    GET_CHANNELS: "GET_CHANNELS",
    UPDATE_CHANNEL: "UPDATE_CHANNEL",
    DELETE_CHANNEL: "DELETE_CHANNEL",

    CREATE_MESSAGE: "CREATE_MESSAGE",
    GET_MESSAGES: "GET_MESSAGES",
    UPDATE_MESSAGE: "UPDATE_MESSAGE",
    DELETE_MESSAGE: "DELETE_MESSAGE",
}

module.exports = actions